---
- hosts: dev-powerdns-01
  become: true
  vars:
    pg_db_name: pdns
    pg_db_user: pdnsuser
    pg_db_pass: pdnspass
    pg_listen_addr: "'127.0.0.1'"
  roles:
    - { role: alpine_postgresql }
    - { role: alpine_powerdns, pdns_authoritive: true, pdns_postgresql: true, pdns_auth_listen_addr: "{{ ansible_eth1.ipv4.address }}" }

- hosts: dev-powerdns-02
  become: true
  roles:
    - { role: alpine_powerdns, pdns_recursor: true, pdns_recursor_listen_addr: "{{ ansible_eth1.ipv4.address }}", pdns_recursor_forward_zones: "powerdns.net=10.0.0.11" }

- hosts: dev-powerdns-03
  become: true
  vars:
    pg_db_name: pdns
    pg_db_user: pdnsuser
    pg_db_pass: pdnspass
    pg_listen_addr: "'127.0.0.1'"
  roles:
    - { role: alpine_postgresql }
    - { role: alpine_powerdns, pdns_recursor: true, pdns_recursor_listen_addr: "{{ ansible_eth1.ipv4.address }}", pdns_recursor_forward_zones: "powerdns.net=127.0.0.1" }
    - { role: alpine_powerdns, pdns_authoritive: true, pdns_postgresql: true, pdns_auth_listen_addr: 127.0.0.1 }

...
