---
- hosts: powerdns01
  become: true
  vars:
    pg_db_name: pdns
    pg_db_user: pdnsuser
    pg_db_pass: pdnspass
  roles:
    - { role: alpine_postgresql }
    - { role: alpine_powerdns, authoritive: true, postgresql: true }
- hosts: powerdns02
  become: true
  roles:
    - { role: alpine_powerdns, recursor: true }
- hosts: powerdns03
  become: true
  vars:
    pg_db_name: pdns
    pg_db_user: pdnsuser
    pg_db_pass: pdnspass
  roles:
    - { role: alpine_postgresql }
    - { role: alpine_powerdns, recursor: true, authoritive: true, postgresql: true }
...
