Vagrant.configure(2) do |config|

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 1024
    vm.linked_clone = true
  end

  config.vm.define "powerdns" do |d1|
    d1.vm.box = "AlpinePlus"
    d1.vm.hostname = "powerdns"
    d1.vm.network "private_network", ip: "10.0.0.101", netmask: "255.255.255.0", virtualbox_intnet: "alpine_network"
    d1.vm.provision "ansible", playbook: "Provision.yml"
  end

end
