Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "jenkins01"
  config.vm.network "private_network", ip: "10.0.0.20", netmask: "255.255.255.0", virtualbox_intnet: "jenkins_network"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provision "shell", path: "Provision.sh"

end
