Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 2048
    vm.name = "OpenNebula"
  end

  config.vm.box = "centos/7"
  config.vm.hostname = "opennebula01"
  config.vm.network "private_network", ip: "10.0.0.167", netmask: "255.255.255.0", virtualbox_intnet: "opennebule_network"
  config.vm.network "forwarded_port", guest: 9869, host: 9869
  config.vm.provision "shell", path: "Provision.sh"

end
