---
# tasks file for alpine_jenkins

- name: Install packages
  apk:
    name: "{{ item }}"
    state: present
  with_items:
      - openjdk8-jre
      - ttf-dejavu
      - fontconfig
      - git
      - ruby
      
- name: Create /opt/jenkins
  file:
     dest: /opt/jenkins
     state: directory
     mode: 0755  

- name: Get the Jenkins WAR
  get_url:
      url: http://mirrors.jenkins-ci.org/war-stable/latest/jenkins.war
      dest: /opt/jenkins/jenkins.war
      
- name: Install Jenkins init.d
  copy:
      src: jenkins.init.d
      dest: /etc/init.d/jenkins
      mode: 0755  

- name: Install Jenkins conf.d
  copy:
      src: jenkins.conf.d
      dest: /etc/conf.d/jenkins
      mode: 0440
      
- name: Start jenkins
  service:
      name: jenkins
      state: started
      enabled: true
         

