Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 1024
    vm.linked_clone = true
  end

  config.vm.define "AnsibleMaster" do |m1|
   m1.vm.box = "centos/7"
   m1.vm.hostname = "ansiblemaster"
   m1.vm.network "private_network", ip: "10.0.0.50", netmask: "255.255.255.0", virtualbox_intnet: "ansible_network"
   m1.vm.provision "shell", path: "Provision.sh"
  end

  config.vm.define "Ansible01" do |a1|
   a1.vm.box = "centos/7"
   a1.vm.hostname = "ansible01"
   a1.vm.network "private_network", ip: "10.0.0.51", netmask: "255.255.255.0", virtualbox_intnet: "ansible_network"
   a1.vm.network "forwarded_port", guest: 80, host: 8080
   a1.vm.provision "shell", path: "Provision.sh"
  end

  config.vm.define "Ansible02" do |a2|
   a2.vm.box = "centos/7"
   a2.vm.hostname = "ansible02"
   a2.vm.network "private_network", ip: "10.0.0.52", netmask: "255.255.255.0", virtualbox_intnet: "ansible_network"
   a2.vm.provision "shell", path: "Provision.sh"
  end

  config.vm.define "Ansible03" do |a3|
   a3.vm.box = "centos/7"
   a3.vm.hostname = "ansible03"
   a3.vm.network "private_network", ip: "10.0.0.53", netmask: "255.255.255.0", virtualbox_intnet: "ansible_network"
   a3.vm.provision "shell", path: "Provision.sh"
  end

end
