Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "pulp01"
  config.vm.network "private_network", ip: "10.0.0.10", netmask: "255.255.255.0", virtualbox_intnet: "pulp_network"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8181
  config.vm.provision "shell", path: "Provision.sh"

end
