cluster = [ { :name => "dev-cassandra-01", :ip => "10.0.0.120" , :net => "dev.net"},
            { :name => "dev-cassandra-02", :ip => "10.0.0.121" , :net => "dev.net"},
            { :name => "dev-cassandra-03", :ip => "10.0.0.122" , :net => "dev.net"} ]

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.linked_clone = true
 end

 config.vm.box = "Alpine"
 config.vm.synced_folder '.', '/vagrant', disabled: true
 cluster.each do |node|
    config.vm.define node[:name] do |config|
      config.vm.hostname = node[:name]
      config.vm.network "private_network", ip: node[:ip], netmask: "255.255.255.0", virtualbox_intnet: node[:net]
      config.vm.provision "ansible", playbook: "Provision.yml"
    end
 end
end
