Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 1024
  end

  config.vm.box = "centos/7"
  config.vm.hostname = "mongo01"
  config.vm.network "private_network", ip: "10.0.0.140", netmask: "255.255.255.0", virtualbox_intnet: "mongo_network"
  config.vm.provision "shell", path: "Provision.sh"

end
