---
- hosts: jenkins01
  become: true

  vars:
    jenkins_plugins:
      - git
      - sonar
      - ssh
      - job-dsl
  roles:
    - geerlingguy.jenkins

  tasks:
    - name: Copy Seed Job to Init
      copy:
        src: create-seed-job.groovy
        dest: /var/lib/jenkins/init.groovy.d/create-seed-job.groovy

    - name: Copy Job to Seed workspace
      copy:
        src: job01.groovy
        dest: /var/lib/jenkins/jobs/SeedJob/workspace/job01.groovy

...
