---
# tasks file for alpine_backdrop

- name: Install packages 
  apk:
    name: "{{ item }}"
    state: present
    update_cache: True
  with_items:
      - ca-certificates
      - unzip
      - php5-json
      - php5-pdo_mysql
      - php5-gd
      - php5-xml
      - php5-dom
      - php5-zip

- name: Download and extract Backdrop
  unarchive:
      src: https://github.com/backdrop/backdrop/releases/download/1.9.0/backdrop.zip
      dest: /var/www/
      remote_src: True
      creates: /var/www/backdrop