Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 4096
    vm.linked_clone = true
  end

 config.vm.define "kubernetes01" do |k1|
  k1.vm.box = "centos/7"
  k1.vm.hostname = "kubernetes01"
  k1.vm.network "private_network", ip: "10.0.0.71", netmask: "255.255.255.0", virtualbox_intnet: "kube_network"
  k1.vm.network "forwarded_port", guest: 8080, host: 8080
  k1.vm.provision "shell", path: "Provision.sh"
 end

 config.vm.define "kubernetes02" do |k2|
  k2.vm.box = "centos/7"
  k2.vm.hostname = "kubernetes02"
  k2.vm.network "private_network", ip: "10.0.0.72", netmask: "255.255.255.0", virtualbox_intnet: "kube_network"
  k2.vm.provision "shell", path: "Provision.sh"
 end

end
