Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.linked_clone = true
    vm.memory = 1024
  end
  config.vm.box = "centos/7"
  config.vm.hostname = "rethinkdb01.lafeberhof.nl"
  config.vm.network "private_network", ip: "10.0.0.190", netmask: "255.255.255.0", virtualbox_intnet: "rethinkdb_network"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provision "shell", path: "Provision.sh"

end
