---
# tasks file for alpine_rabbitmq

- name: Enable edge testing repository
  replace:
    dest: /etc/apk/repositories
    regexp: "#http://dl-cdn.alpinelinux.org/alpine/edge/community"
    replace: "http://dl-cdn.alpinelinux.org/alpine/edge/testing"

- name: Install RabbitMQ package
  apk:
    name: rabbitmq-server
    state: present
    update_cache: yes
    
- name: Create /etc/rabbitmq
  file:
     dest: /etc/rabbitmq
     state: directory
     mode: 0755
     
- name: Create erlang_cookie
  lineinfile:
     path: /usr/lib/rabbitmq/.erlang.cookie
     line: '{{ rabbitmq_cookie }}'
     state: present
     create: true
     owner: rabbitmq
     group: rabbitmq
     mode: 0600

- name: Start RabbitMQ
  service:
      name: rabbitmq-server
      state: started
      enabled: true
         
...   