Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 1024
    vm.name = "kibana01"
  end

  config.vm.box = "centos/7"
  config.vm.hostname = "kibana01"
  config.vm.network "private_network", ip: "10.0.0.145", netmask: "255.255.255.0", virtualbox_intnet: "kibana_network"
  config.vm.network "forwarded_port", guest: 5601, host: 5601
  config.vm.provision "shell", path: "Provision.sh"

end
