---
# tasks file for alpine_kapacitor

- name: Install packages
  apk:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
      - ca-certificates
      - tar

- name: Create /opt/kapacitor directories
  file:
     dest: "{{ item }}"
     state: directory
     mode: 0755  
  with_items:
      - /opt/metadata
      - /opt/replay
      - /opt/tasks

- name: Create /etc/kapacitor
  file:
     dest: /etc/kapacitor
     state: directory
     mode: 0755

- name: Get Kapacitor
  unarchive:
      src: https://dl.influxdata.com/kapacitor/releases/kapacitor-{{ kapacitor_version }}-static_linux_amd64.tar.gz
      dest: /opt
      remote_src: True
      extra_opts: "--strip-components=2"
      creates: /opt/kapacitor

- name: Delete /opt/kapacitor.conf
  file:
    state: absent
    path: /opt/kapacitor.conf
      
- name: Install Kapacitor .conf
  copy:
      src: kapacitor.conf
      dest: /etc/kapacitor/kapacitor.conf
      mode: 0755

- name: Install Kapacitor init.d
  copy:
      src: kapacitor.init.d
      dest: /etc/init.d/kapacitor
      mode: 0755  

- name: Install Kapacitor conf.d
  copy:
      src: kapacitor.conf.d
      dest: /etc/conf.d/kapacitor
      mode: 0440
      
- name: Start Kapacitor 
  service:
      name: kapacitor
      state: started
      enabled: true
         
...
