Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 1024
    vm.name = "sensu01"
  end

  config.vm.box = "centos/7"
  config.vm.hostname = "sensu01"
  config.vm.network "private_network", ip: "10.0.0.210", netmask: "255.255.255.0", virtualbox_intnet: "sensu_network"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.provision "shell", path: "Provision.sh"

end
