Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 1024
    vm.linked_clone = true
  end

  config.vm.define "Varnish01" do |v1|
    v1.vm.box = "debian/jessie64"
    v1.vm.hostname = "varnish01"
    v1.vm.network "private_network", ip: "10.0.0.10", netmask: "255.255.255.0", virtualbox_intnet: "varnish_network"
    v1.vm.network "forwarded_port", guest: 80, host: 8080
    v1.vm.provision "shell", path: "Provision.sh"
  end

end
