---
# tasks file for alpine_metricbeat

- name: Install packages
  apk:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
      - ca-certificates
      - tar
      
- name: Get the key for glibc 
  get_url:
    url: https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub
    dest: /etc/apk/keys/sgerrand.rsa.pub
    mode: 0440

- name: Get glibc 
  get_url:
    url: https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.25-r0/glibc-2.25-r0.apk
    dest: /tmp/glibc-2.25-r0.apk
    mode: 0440

- name: Install packages glibc
  apk:
    name: /tmp/glibc-2.25-r0.apk
    state: present
     
- name: Create /opt
  file:
     dest: /opt
     state: directory
     mode: 0755  

- name: Get Metricbeat 
  unarchive:
      src: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{{ metricbeat_version }}.tar.gz
      dest: /opt
      remote_src: True
      creates: /opt/metricbeat-{{ metricbeat_version }}

- name: Configure Metricbeat
  template: 
      src: metricbeat.yml.j2
      dest: /opt/metricbeat-{{ metricbeat_version }}/metricbeat.yml
      mode: 0644
      
- name: Install Metricbeat init.d
  template:
      src: metricbeat.init.d.j2
      dest: /etc/init.d/metricbeat
      mode: 0755  

- name: Install Metricbeat conf.d
  copy:
      src: metricbeat.conf.d
      dest: /etc/conf.d/metricbeat
      mode: 0440
      
- name: Start metricbeat
  service:
      name: metricbeat
      state: started
      enabled: true
         

