cluster = [ { :name => "dev-host01", :ip => "10.0.0.11" },
            { :name => "dev-host02", :ip => "10.0.0.12" },
            { :name => "dev-host03", :ip => "10.0.0.13" } ]

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.linked_clone = true
 end
 config.vm.box = "Alpine"
 config.vm.synced_folder '.', '/vagrant', disabled: true
 cluster.each do |opts|
    config.vm.define opts[:name] do |config|
    config.vm.hostname = opts[:name]
    config.vm.network "private_network", ip: opts[:ip], netmask: "255.255.255.0", virtualbox_intnet: "dev.net"
    config.vm.provision "ansible", playbook: "Provision.yml"
    end
 end
end
