Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 1024
  end

  config.vm.box = "centos/7"
  config.vm.hostname = "rabbitmq01"
  config.vm.network "private_network", ip: "10.0.0.230", netmask: "255.255.255.0", virtualbox_intnet: "rabbitmq_network"
  config.vm.provision "shell", path: "Provision.sh"
  config.vm.network "forwarded_port", guest: 15672, host: 15672

end
