---
# tasks file for alpine_graphite

- name: Install packages needed
  apk:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
      - alpine-sdk
      - python-dev
      - libffi-dev
      - py2-pip
      - libffi
      - py2-cairo
      
- name: Install Carbon, Whisper and Graphite-Web via pip
  pip:
     name: "{{ item }}"
  with_items:
       - https://github.com/graphite-project/whisper/tarball/master
       - https://github.com/graphite-project/carbon/tarball/master
       - https://github.com/graphite-project/graphite-web/tarball/master
       - gunicorn
  register: graphite_web_installed
       
- name: Build graphite-web database
  command: sudo PYTHONPATH=/opt/graphite/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb
  when: 
    - graphite_web_installed is defined

       
- name: Install init.d carbon-cache
  copy:
     src: carbon-cache.init.d
     dest: /etc/init.d/carbon-cache
     mode: 0755
    
- name: Install conf.d carbon-cache
  copy:
     src: carbon-cache.conf.d
     dest: /etc/conf.d/carbon-cache
     mode: 0440

- name: Install nginx.conf for graphite-web
  template:
     src: nginx.conf.j2
     dest: /etc/nginx/conf.d/default.conf
     mode: 0755
  notify: Reload nginx

- name: Install init.d graphite-web
  copy:
     src: graphite-web.init.d
     dest: /etc/init.d/graphite-web
     mode: 0755

- name: Install conf.d Graphite-web
  copy:
     src: graphite-web.conf.d
     dest: /etc/conf.d/graphite-web
     mode: 0440

- name: Configure Carbon-cache
  copy:
     src: carbon-cache/{{ item }}
     dest: /opt/graphite/conf/{{ item }}
  with_items: 
      - carbon.conf
      - storage-schemas.conf

- name: Start Carbon-cache
  service:
      name: carbon-cache
      state: started
      enabled: true

- name: Start Graphite-web
  service:
      name: graphite-web
      state: started
      enabled: true
