Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.linked_clone = true
    vm.memory = 1024
  end
  config.vm.box = "centos/7"
  config.vm.hostname = "powerdns01.lafeberhof.nl"
  config.vm.network "private_network", ip: "10.0.0.170", netmask: "255.255.255.0", virtualbox_intnet: "powerdns_network"
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.provision "shell", path: "Provision.sh"

end
