Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 1024
    vm.linked_clone = true
  end

  config.vm.define "Confluence01" do |c1|
    c1.vm.box = "debian/jessie64"
    c1.vm.hostname = "confluence01"
    c1.vm.network "private_network", ip: "10.0.0.133", netmask: "255.255.255.0", virtualbox_intnet: "confluence_network"
    c1.vm.network "forwarded_port", guest: 80, host: 8080
    c1.vm.provision "shell", path: "Provision.sh"
  end

end
