---
# tasks file for alpine_mariadb

- name: Install MariaDB
  apk:
    name: mariadb
    state: present
    update_cache: yes

- name: Install MariaDB Python module
  apk:
    name: py-mysqldb
    state: present
    update_cache: yes

- name: Init MariaDB
  shell: "/etc/init.d/mariadb setup"
  args:
    creates: /var/lib/mysql/mysql/

- name: Listen on socket only
  ini_file:
    dest: '/etc/mysql/my.cnf'
    section: mysqld
    option: skip-networking
    value: on
  when: mariadb_listen_addr is undefined
  notify: Restart mariadb

- name: Change listen address
  ini_file:
    dest: '/etc/mysql/my.cnf'
    section: mysqld
    option: bind-address
    value: "{{ mariadb_listen_addr }}"
  when: mariadb_listen_addr is defined
  notify: Restart mariadb

- name: Listen NOT on socket only
  ini_file:
    dest: '/etc/mysql/my.cnf'
    section: mysqld
    option: skip-networking
    value: off
  when: mariadb_listen_addr is defined
  notify: Restart mariadb

- name: Start MariaDB
  service:
    name: mariadb
    state: started
    enabled: true

- name: Create MariaDB database {{ mysql_db_name }}
  mysql_db:
    name: "{{ mysql_db_name }}"
    state: present

- name: Create MariaDB User {{ mysql_db_user }} of {{ mysql_db_name }}
  mysql_user:
    name: "{{ mysql_db_user }}"
    password: "{{ mysql_db_pass }}"
    priv: '{{ mysql_db_name }}.*:ALL'
    state: present
