Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 8192
    vm.cpus = 2
    vm.linked_clone = true
  end

  config.vm.box = "centos/7"
  config.vm.hostname = "katello01"
  config.vm.network "private_network", ip: "10.0.0.142", netmask: "255.255.255.0", virtualbox_intnet: "katello_network"
  config.vm.provision "shell", path: "Provision.sh"

end
