Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "prometheus01"
  config.vm.network "private_network", ip: "10.0.0.220", netmask: "255.255.255.0", virtualbox_intnet: "prometheus_network"
  config.vm.network "forwarded_port", guest: 9100, host: 9100
  config.vm.network "forwarded_port", guest: 9090, host: 9090
  config.vm.provision "shell", path: "Provision.sh"

end
