Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 2048
    vm.linked_clone = true
  end

  config.vm.define "ElasticBackup" do |eb|
   eb.vm.box = "centos/7"
   eb.vm.hostname = "elasticbackup"
   eb.vm.network "private_network", ip: "10.0.0.123", netmask: "255.255.255.0", virtualbox_intnet: "elasticsearch_network"
   eb.vm.provision "shell", path: "ProvisionEB.sh"
  end

  config.vm.define "ElasticNode01" do |n1|
   n1.vm.box = "centos/7"
   n1.vm.hostname = "elasticsearch01"
   n1.vm.network "private_network", ip: "10.0.0.120", netmask: "255.255.255.0", virtualbox_intnet: "elasticsearch_network"
   n1.vm.network "forwarded_port", guest: 9200, guest_ip: "10.0.0.120", host: 9200
   n1.vm.provision "shell", path: "Provision01.sh"
  end
  config.vm.define "ElasticNode02" do |n2|
   n2.vm.box = "centos/7"
   n2.vm.hostname = "elasticsearch02"
   n2.vm.network "private_network", ip: "10.0.0.121", netmask: "255.255.255.0", virtualbox_intnet: "elasticsearch_network"
   n2.vm.provision "shell", path: "Provision02.sh"
  end
  config.vm.define "ElasticNode03" do |n3|
   n3.vm.box = "centos/7"
   n3.vm.hostname = "elasticsearch03"
   n3.vm.network "private_network", ip: "10.0.0.122", netmask: "255.255.255.0", virtualbox_intnet: "elasticsearch_network"
   n3.vm.provision "shell", path: "Provision03.sh"
  end

  config.vm.define "Kibana" do |kb|
   kb.vm.box = "centos/7"
   kb.vm.hostname = "kibana"
   kb.vm.network "private_network", ip: "10.0.0.124", netmask: "255.255.255.0", virtualbox_intnet: "elasticsearch_network"
   kb.vm.network "forwarded_port", guest: 5601, host: 5601
   kb.vm.provision "shell", path: "ProvisionKB.sh"
  end

  config.vm.define "Grafana" do |gf|
   gf.vm.box = "centos/7"
   gf.vm.hostname = "grafana"
   gf.vm.network "private_network", ip: "10.0.0.125", netmask: "255.255.255.0", virtualbox_intnet: "elasticsearch_network"
   gf.vm.network "forwarded_port", guest: 3000, host: 3000
   gf.vm.provision "shell", path: "ProvisionGF.sh"
  end

  config.vm.define "Graphite" do |gr|
   gr.vm.box = "centos/7"
   gr.vm.hostname = "graphite"
   gr.vm.network "private_network", ip: "10.0.0.126", netmask: "255.255.255.0", virtualbox_intnet: "elasticsearch_network"
   gr.vm.network "forwarded_port", guest: 80, host: 8080
   gr.vm.provision "shell", path: "ProvisionGR.sh"
  end

  config.vm.define "Logstash" do |ls|
   ls.vm.box = "centos/7"
   ls.vm.hostname = "logstash"
   ls.vm.network "private_network", ip: "10.0.0.127", netmask: "255.255.255.0", virtualbox_intnet: "elasticsearch_network"
   ls.vm.provision "shell", path: "ProvisionLS.sh"
  end


end

