Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 2048
  end

  config.vm.box = "centos/7"
  config.vm.hostname = "elasticsearch01"
  config.vm.network "private_network", ip: "10.0.0.120", netmask: "255.255.255.0", virtualbox_intnet: "elasticsearch_network"
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.provision "shell", path: "Provision.sh"

end
