---
# tasks file for alpine_nginx

- name: Install Nginx
  apk:
    name: nginx
    state: present
    update_cache: yes

- name: Install php5 php-fpm 
  apk:
    name: php5-fpm
    state: present
    update_cache: yes
  when: php5 is defined

- name: Install php7 php-fpm 
  apk:
    name: php7-fpm
    state: present
    update_cache: yes
  when: php7 is defined

- name: Configure a default nginx  
  template: 
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    
- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Start PHP-fpm for php5
  service:
    name: php-fpm
    state: started
    enabled: true
  when: php5 is defined

- name: Start PHP-fpm for php7
  service:
    name: php-fpm7
    state: started
    enabled: true
  when: php7 is defined

...