Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 2048
  end

  config.vm.box = "centos/7"
  config.vm.hostname = "rocketchat01"
  config.vm.network "private_network", ip: "10.0.0.60", netmask: "255.255.255.0", virtualbox_intnet: "rocketchat_network"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.provision "shell", path: "Provision.sh"

end
