---
# tasks file for alpine_rocketchat

- name: Enable edge 3.3 community repository
  lineinfile:
    dest: /etc/apk/repositories
    line: "http://dl-cdn.alpinelinux.org/alpine/v3.3/main"


- name: Install NodeJS (version 4) package
  apk:
    name: "nodejs<5.0.0"
    state: present
    update_cache: yes
    
- name: Install packages needed by RocketChat
  apk:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
     - alpine-sdk
     - graphicsmagick
     - tar

- name: Check if user excists
  getent: 
      database: passwd
      key: rocketchat
      fail_key: false
      
- name: Create user for RocketChat
  command: adduser rocketchat -DH -s /sbin/nologin
  when: not getent_passwd.rocketchat

- name: Create /opt/rocketchat
  file:
     dest: /opt/rocketchat
     state: directory
     mode: 0755

- name: Create log directory
  file:
     dest: /var/log/rocketchat
     owner: rocketchat
     group: rocketchat
     state: directory
     mode: 0770  
 

- name: Install init.d
  copy:
     src: rocketchat.init.d
     dest: /etc/init.d/rocketchat
     mode: 0755
    
- name: Install conf.d
  template:
     src: rocketchat.conf.d.j2
     dest: /etc/conf.d/rocketchat
     mode: 0440
   
- name: Download and extract RocketChat
  unarchive:
     src: https://rocket.chat/releases/latest/download
     dest: /opt/rocketchat
     remote_src: True
     validate_certs: False
     creates: /opt/rocketchat/bundle 

- name: Install RocketChat using nmp
  npm:
      state: present
      path: /opt/rocketchat/bundle/programs/server
      executable: /usr/bin/npm
  
- name: Let user own /opt/rocketchat
  file:
     dest: /opt/rocketchat
     state: directory
     owner: rocketchat
     group: rocketchat
     recurse: true

- name: Start RocketChat
  service:
      name: rocketchat
      state: started
      enabled: true
