---
# tasks file for alpine_rocketchat

- name: Enable edge 3.3 community repository
  lineinfile:
    dest: /etc/apk/repositories
    line: "http://dl-cdn.alpinelinux.org/alpine/v3.3/main"


- name: Install NodeJS (version 4) package
  apk:
    name: "nodejs<5.0.0"
    state: present
    update_cache: yes
    
- name: Install packages needed by Rocketchat
  apk:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
     - alpine-sdk
     - graphicsmagick
     - tar

- name: Create /opt/rocketchat
  file:
     dest: /opt/rocketchat
     state: directory
     mode: 0755  

- name: Install init.d
  copy:
     src: rocketchat.init.d
     dest: /etc/init.d/rocketchat
     mode: 0755
    
- name: Install conf.d
  copy:
     src: rocketchat.conf.d
     dest: /etc/conf.d/rocketchat
     mode: 0440
   
- name: Download and extract RocketChat
  unarchive:
     src: https://rocket.chat/releases/latest/download
     dest: /opt/rocketchat
     remote_src: True
     validate_certs: False
     creates: /opt/rocketchat/bundle 
   
- name: Run node install on RocketChat source
  shell: "cd /opt/rocketchat/bundle/programs/server && /usr/bin/npm install --unsafe-perm && touch /root/build.done"
  args:
    creates: /root/build.done 
  
- name: Start RocketChat
  service:
      name: rocketchat
      state: started
      enabled: true
