---
- hosts: dev-postgresql-01
  become: true
  roles:
    - { role: alpine_postgresql, primary: true, pg_db_name: test, pg_db_user: testuser, pg_db_pass: testpass }
- hosts: dev-postgresql-02
  become: true
  roles:
    - { role: alpine_postgresql, standby: true }
...
