Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 1024
    vm.linked_clone = true
  end

  config.vm.define "postgresql" do |d1|
    d1.vm.box = "maier/alpine-3.4-x86_64"
    d1.vm.hostname = "postgresql"
    d1.vm.network "private_network", ip: "10.0.0.100", netmask: "255.255.255.0", virtualbox_intnet: "alpine_network"
    d1.vm.provision "ansible", playbook: "Provision.yml"
  end

end
