---
# tasks file for alpine_elasticsearch

- name: Install packages
  apk:
    name: "{{ item }}"
    state: present
    update_cache: True
  with_items:
      - openjdk8-jre
      - tar

- name: Check if user excists
  getent: 
      database: passwd
      key: elsearch
      fail_key: false
      
- name: Create user for elasticsearch
  command: adduser elsearch -DH -s /sbin/nologin
  when: not getent_passwd.elsearch

- name: Create /opt
  file:
     dest: /opt
     state: directory
     mode: 0755  
     
- name: Create log directory
  file:
     dest: /var/log/elasticsearch
     owner: elsearch
     group: elsearch
     state: directory
     mode: 0770  
  
- name: Get Elasticsearch source
  unarchive:
      src: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}.tar.gz
      dest: /opt
      remote_src: True
      creates: /opt/elasticsearch-{{ elasticsearch_version }}

- name: Let user own /opt/elasticsearch-{{ elasticsearch_version }}
  file:
     dest: /opt/elasticsearch-{{ elasticsearch_version }}
     state: directory
     owner: elsearch
     group: elsearch
     recurse: true
     
- name: Set sysctl value fs.file-max
  sysctl: 
      name: fs.file-max
      value: 70000
      state: present

- name: Set sysctl value vm.max_map_count
  sysctl: 
      name: vm.max_map_count
      value: 262144
      state: present
     
- name: Configure Elasticsearch
  template: 
      src: elasticsearch.yml.j2
      dest: /opt/elasticsearch-{{ elasticsearch_version }}/config/elasticsearch.yml
      mode: 0644
  
- name: Install Elasticsearch init.d
  template:
      src: elasticsearch.init.d.j2
      dest: /etc/init.d/elasticsearch
      mode: 0755  

- name: Install Elasticsearch conf.d
  copy:
      src: elasticsearch.conf.d
      dest: /etc/conf.d/elasticsearch
      mode: 0440
      
- name: Start Elasticsearch
  service:
      name: elasticsearch
      state: started
      enabled: true

...