Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 4096
    vm.linked_clone = true
  end

  config.vm.define "debian9" do |d1|
    d1.vm.box = "debian/stretch64"
    d1.vm.hostname = "debian9"
    d1.vm.network "private_network", ip: "10.0.0.100", netmask: "255.255.255.0", virtualbox_intnet: "debian9_network"
    d1.vm.provision "ansible", playbook: "Provision.yml"
  end

end
