---
# tasks file for alpine_telegraf

- name: Install packages
  apk:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
      - ca-certificates
      - tar

- name: Create /opt
  file:
     dest: /opt
     state: directory
     mode: 0755  

- name: Create /etc/telegraf
  file:
     dest: /etc/telegraf
     state: directory
     mode: 0755  

- name: Get Telegraf
  unarchive:
      src: https://dl.influxdata.com/telegraf/releases/telegraf-{{ telegraf_version }}-static_linux_amd64.tar.gz
      dest: /opt
      remote_src: True
      extra_opts: "--strip-components=2"
      creates: /opt/telegraf

- name: Delete /opt/telegraf.conf
  file:
    state: absent
    path: /opt/telegraf.conf
      
- name: Install Telegraf .conf
  copy:
      src: telegraf.conf
      dest: /etc/telegraf/telegraf.conf
      mode: 0755

- name: Install Telegraf init.d
  copy:
      src: telegraf.init.d
      dest: /etc/init.d/telegraf
      mode: 0755  

- name: Install Telegraf conf.d
  copy:
      src: telegraf.conf.d
      dest: /etc/conf.d/telegraf
      mode: 0440
      
- name: Start Telegraf 
  service:
      name: telegraf
      state: started
      enabled: true
         
...
