---
# tasks file for alpine_nginx

- name: Install Nginx
  apk:
    name: nginx
    state: present
    update_cache: yes

- name: Install php5 php-fpm 
  apk:
    name: php5-fpm
    state: present
    update_cache: yes
  when: php5 is defined

- name: Install php7 php-fpm 
  apk:
    name: php7-fpm
    state: present
    update_cache: yes
  when: php7 is defined

- name: Configure a default nginx conf
  template: 
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: Reload nginx

- name: Configure a default nginx index.html
  template: 
    src: index.html.j2
    dest: /var/www/localhost/htdocs/index.html
    
- name: Configure a default nginx index.php
  template: 
    src: index.php.j2
    dest: /var/www/localhost/htdocs/index.php
  when: php5 is defined or php7 is defined
    
- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Start PHP-fpm for php5
  service:
    name: php-fpm
    state: started
    enabled: true
  when: php5 is defined

- name: Start PHP-fpm for php7
  service:
    name: php-fpm7
    state: started
    enabled: true
  when: php7 is defined

...
