Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.linked_clone = true
    vm.memory = 1024
  end
  config.vm.box = "centos/7"
  config.vm.hostname = "mosquitto01.lafeberhof.nl"
  config.vm.network "private_network", ip: "10.0.0.180", netmask: "255.255.255.0", virtualbox_intnet: "mosquitto_network"
  config.vm.network "forwarded_port", guest: 1883, host: 1883
  config.vm.provision "shell", path: "Provision.sh"

end
