Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 4096
  end
  config.vm.box = "centos/7"
  config.vm.hostname = "postgresql01.lafeberhof.nl"
  config.vm.network "private_network", ip: "10.0.0.160", netmask: "255.255.255.0", virtualbox_intnet: "postgresql_network"
  config.vm.network "forwarded_port", guest: 5432, host: 5432
  config.vm.provision "shell", path: "Provision.sh"

end
