Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 1024
    vm.linked_clone = true
  end

  config.vm.define "Redis01" do |r1|
   r1.vm.box = "centos/7"
   r1.vm.hostname = "redis01"
   r1.vm.network "private_network", ip: "10.0.0.151", netmask: "255.255.255.0", virtualbox_intnet: "redis_network"
   r1.vm.provision "shell", path: "Provision.sh"
  end

  config.vm.define "Redis02" do |r2|
   r2.vm.box = "centos/7"
   r2.vm.hostname = "redis02"
   r2.vm.network "private_network", ip: "10.0.0.152", netmask: "255.255.255.0", virtualbox_intnet: "redis_network"
   r2.vm.provision "shell", path: "Provision.sh"
  end

  config.vm.define "Redis03" do |r3|
   r3.vm.box = "centos/7"
   r3.vm.hostname = "redis03"
   r3.vm.network "private_network", ip: "10.0.0.153", netmask: "255.255.255.0", virtualbox_intnet: "redis_network"
   r3.vm.provision "shell", path: "Provision.sh"
  end


end
